version: '3.7'

services:
  node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    container_name: node-docker
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev